 plgrid/libs/hdf5/1.10.4 unloaded.
 plgrid/tools/impi/2018 unloaded.
 plgrid/libs/mkl/2018.0.0 unloaded.
 plgrid/libs/boost/1.66.0 unloaded.
 plgrid/tools/swig/3.0.12 unloaded.
 plgrid/tools/gcc/6.4.0 unloaded.
 plgrid/tools/intel/18.0.0 unloaded.
 plgrid/libs/libxc/4.2.3 unloaded.
 plgrid/tools/python/3.7 unloaded.
 plgrid/tools/binutils/2.34 loaded.
 plgrid/tools/gcc/9.3.0 loaded.
 plgrid/tools/intel/19.1.1 loaded.
 plgrid/tools/impi/2018.5 loaded.
 plgrid/libs/hdf5/1.12.0 loaded.
 plgrid/libs/mkl/2020.0.1 loaded.
 plgrid/libs/icu/61.1 loaded.
 plgrid/libs/boost/1.73.0-python-3.8 loaded.
 plgrid/tools/swig/4.0.1 loaded.
 plgrid/libs/libxc/5.0.0 loaded.
 plgrid/tools/tcltk//8.6.10 loaded.
 plgrid/apps/cuda/11.2 loaded.
    *********************** IMPORTANT / LICENSING INFORMATION
****************************
    By using plgrid/libs/cudnn/8.1.1-cuda-11.2 module you accept NVIDIA cuDNN
SLA
    available at https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
    *********************** IMPORTANT / LICENSING INFORMATION
**************************** 
 plgrid/libs/cudnn/8.1.1-cuda-11.2 loaded.
 plgrid/tools/python/3.8 loaded.

The following have been reloaded with a version change:
  1) plgrid/libs/boost/1.66.0 => plgrid/libs/boost/1.73.0-python-3.8
  2) plgrid/libs/hdf5/1.10.4 => plgrid/libs/hdf5/1.12.0
  3) plgrid/libs/libxc/4.2.3 => plgrid/libs/libxc/5.0.0
  4) plgrid/libs/mkl/2018.0.0 => plgrid/libs/mkl/2020.0.1
  5) plgrid/tools/gcc/6.4.0 => plgrid/tools/gcc/9.3.0
  6) plgrid/tools/impi/2018 => plgrid/tools/impi/2018.5
  7) plgrid/tools/intel/18.0.0 => plgrid/tools/intel/19.1.1
  8) plgrid/tools/python/3.7 => plgrid/tools/python/3.8
  9) plgrid/tools/swig/3.0.12 => plgrid/tools/swig/4.0.1

 plgrid/apps/cuda/11.2 unloaded.
 plgrid/apps/cuda/11.2 loaded.
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0)
ERROR: No matching distribution found for tensorflow==1.15
WARNING: You are using pip version 21.1.3; however, version 21.2.4 is available.
You should consider upgrading via the '/net/software/local/python/3.8/bin/python3 -m pip install --upgrade pip' command.
WARNING - utils - No observers have been added to this run
INFO - utils - Running command 'train'
INFO - utils - Started
/net/software/local/python/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py:2223: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '
ERROR - utils - Failed after 0:00:50!
Traceback (most recent calls WITHOUT Sacred internals):
  File "train.py", line 33, in train
    model, checkpoint_path, kl_alpha = get_model(input_shape,
  File "/net/people/plgforobohd/3d-cnn-prometheus/network/model.py", line 120, in get_model
    loss = variational_free_energy_loss(model, scale_factor, kl_alpha)
  File "/net/people/plgforobohd/3d-cnn-prometheus/network/utils.py", line 71, in variational_free_energy_loss
    kl = sum(model.losses) / scale_factor
  File "/net/software/local/python/3.8/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1400, in r_binary_op_wrapper
    return func(x, y, name=name)
  File "/net/software/local/python/3.8/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/net/software/local/python/3.8/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1700, in _add_dispatch
    return gen_math_ops.add_v2(x, y, name=name)
  File "/net/software/local/python/3.8/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 459, in add_v2
    return add_v2_eager_fallback(
  File "/net/software/local/python/3.8/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 483, in add_v2_eager_fallback
    _result = _execute.execute(b"AddV2", 1, inputs=_inputs_flat, attrs=_attrs,
  File "/net/software/local/python/3.8/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 75, in quick_execute
    raise e
  File "/net/software/local/python/3.8/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: conv3d_flipout/divergence_kernel:0

